"""
Workspace Import MPP fixture: 20000 leaf tasks under 10 phase summaries.

Structure (same as workspace-mpp-import-test.xml — NOT a portfolio):
  L1 = phases (summary)
  L2 = leaf tasks

Output:
  - workspace-mpp-20000.xml

Run:
  python scripts/fixtures/workspace-tasks-4000/gen-workspace-mpp-20000.py
"""

from __future__ import annotations

import html
from datetime import date, timedelta
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

PHASE_COUNT = 10
TASKS_PER_PHASE = 2000  # 10 × 2000 = 20000 leaf tasks
START = date(2026, 1, 5)
PROJECT_NAME = "Workspace MPP Load 20000"


def add_days(d: date, n: int) -> date:
    return d + timedelta(days=n)


def iso_dt(d: date, end: bool = False) -> str:
    return f"{d.isoformat()}T{'17' if end else '08'}:00:00"


def phase_window(phase_index: int) -> tuple[date, date]:
    start = add_days(START, phase_index * 45)
    end = add_days(start, 44)
    return start, end


def task_window(phase_index: int, task_index: int) -> tuple[date, date]:
    phase_start, _ = phase_window(phase_index)
    start = add_days(phase_start, task_index % 40)
    end = add_days(start, 2)
    return start, end


def phase_name(phase_index: int) -> str:
    n = phase_index + 1
    return f"Phase {n:02d} — Workstream {n}"


def escape(text: str) -> str:
    return html.escape(text, quote=False)


def write_task(
    out,
    *,
    uid: int,
    tid: int,
    name: str,
    outline_level: int,
    outline_number: str,
    wbs: str,
    summary: bool,
    start: date,
    finish: date,
    duration: str,
    milestone: bool = False,
    predecessors: list[int] | None = None,
) -> None:
    preds = predecessors or []
    pred_xml = "\n".join(
        f"""      <PredecessorLink>
        <PredecessorUID>{p}</PredecessorUID>
        <Type>1</Type>
        <CrossProject>0</CrossProject>
        <LinkLag>0</LinkLag>
        <LagFormat>7</LagFormat>
      </PredecessorLink>"""
        for p in preds
    )
    out.write(
        f"""    <Task>
      <UID>{uid}</UID>
      <ID>{tid}</ID>
      <Name>{escape(name)}</Name>
      <Type>{1 if summary else 0}</Type>
      <IsNull>0</IsNull>
      <OutlineLevel>{outline_level}</OutlineLevel>
      <OutlineNumber>{outline_number}</OutlineNumber>
      <WBS>{wbs}</WBS>
      <Summary>{1 if summary else 0}</Summary>
      <Critical>{0 if summary else 1}</Critical>
      <Priority>500</Priority>
      <Start>{iso_dt(start)}</Start>
      <Finish>{iso_dt(finish, end=True)}</Finish>
      <Duration>{duration}</Duration>
      <Manual>0</Manual>
      <PercentComplete>0</PercentComplete>
      <Milestone>{1 if milestone else 0}</Milestone>
{pred_xml}
    </Task>
"""
    )


def main() -> None:
    project_end = add_days(START, PHASE_COUNT * 45)
    xml_path = OUT_DIR / "workspace-mpp-20000.xml"
    deps = 0
    leaf = 0
    uid = 1
    tid = 1

    with xml_path.open("w", encoding="utf-8", newline="\n") as out:
        out.write(
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
  Workspace Import MPP load fixture (single project — NOT a portfolio).

  How to test:
  1) Open any existing project workspace.
  2) Import MPP → select workspace-mpp-20000.xml → Confirm.
  3) Expect: {PHASE_COUNT} phases, {PHASE_COUNT * TASKS_PER_PHASE} tasks,
     FS deps every 10th task within each phase.

  Structure (L1 = phases, L2 = tasks):
    Phase 01 — Workstream 1
      WS Task 1.0001 …
    …

  Generated by gen-workspace-mpp-20000.py — do not hand-edit.
-->
<Project xmlns="http://schemas.microsoft.com/project">
  <Name>{escape(PROJECT_NAME)}</Name>
  <Title>{escape(PROJECT_NAME)}</Title>
  <Company>Cybsec PMO</Company>
  <Author>Cybsec PMO Load Fixture</Author>
  <CreationDate>2026-01-01T09:00:00</CreationDate>
  <LastSaved>2026-01-01T09:00:00</LastSaved>
  <ScheduleFromStart>1</ScheduleFromStart>
  <StartDate>{iso_dt(START)}</StartDate>
  <FinishDate>{iso_dt(project_end, end=True)}</FinishDate>
  <CalendarUID>1</CalendarUID>
  <DefaultStartTime>08:00:00</DefaultStartTime>
  <DefaultFinishTime>17:00:00</DefaultFinishTime>
  <MinutesPerDay>480</MinutesPerDay>
  <MinutesPerWeek>2400</MinutesPerWeek>
  <DaysPerMonth>20</DaysPerMonth>
  <CurrencyCode>USD</CurrencyCode>
  <Calendars>
    <Calendar>
      <UID>1</UID>
      <Name>Standard</Name>
      <IsBaseCalendar>1</IsBaseCalendar>
      <BaseCalendarUID>-1</BaseCalendarUID>
      <WeekDays>
        <WeekDay><DayType>1</DayType><DayWorking>0</DayWorking></WeekDay>
        <WeekDay><DayType>2</DayType><DayWorking>1</DayWorking><WorkingTimes><WorkingTime><FromTime>08:00:00</FromTime><ToTime>12:00:00</ToTime></WorkingTime><WorkingTime><FromTime>13:00:00</FromTime><ToTime>17:00:00</ToTime></WorkingTime></WorkingTimes></WeekDay>
        <WeekDay><DayType>3</DayType><DayWorking>1</DayWorking><WorkingTimes><WorkingTime><FromTime>08:00:00</FromTime><ToTime>12:00:00</ToTime></WorkingTime><WorkingTime><FromTime>13:00:00</FromTime><ToTime>17:00:00</ToTime></WorkingTime></WorkingTimes></WeekDay>
        <WeekDay><DayType>4</DayType><DayWorking>1</DayWorking><WorkingTimes><WorkingTime><FromTime>08:00:00</FromTime><ToTime>12:00:00</ToTime></WorkingTime><WorkingTime><FromTime>13:00:00</FromTime><ToTime>17:00:00</ToTime></WorkingTime></WorkingTimes></WeekDay>
        <WeekDay><DayType>5</DayType><DayWorking>1</DayWorking><WorkingTimes><WorkingTime><FromTime>08:00:00</FromTime><ToTime>12:00:00</ToTime></WorkingTime><WorkingTime><FromTime>13:00:00</FromTime><ToTime>17:00:00</ToTime></WorkingTime></WorkingTimes></WeekDay>
        <WeekDay><DayType>6</DayType><DayWorking>1</DayWorking><WorkingTimes><WorkingTime><FromTime>08:00:00</FromTime><ToTime>12:00:00</ToTime></WorkingTime><WorkingTime><FromTime>13:00:00</FromTime><ToTime>17:00:00</ToTime></WorkingTime></WorkingTimes></WeekDay>
        <WeekDay><DayType>7</DayType><DayWorking>0</DayWorking></WeekDay>
      </WeekDays>
    </Calendar>
  </Calendars>
  <Tasks>
"""
        )

        for ph in range(PHASE_COUNT):
            phase_no = ph + 1
            phase_start, phase_end = phase_window(ph)
            pname = phase_name(ph)
            phase_uid = uid
            write_task(
                out,
                uid=phase_uid,
                tid=tid,
                name=pname,
                outline_level=1,
                outline_number=str(phase_no),
                wbs=str(phase_no),
                summary=True,
                start=phase_start,
                finish=phase_end,
                duration="PT360H0M0S",
            )
            uid += 1
            tid += 1

            last_leaf_uid: int | None = None
            for t in range(TASKS_PER_PHASE):
                task_no = t + 1
                t_start, t_end = task_window(ph, t)
                name = f"WS Task {phase_no}.{task_no:04d}"
                preds: list[int] = []
                if task_no > 1 and task_no % 10 == 1 and last_leaf_uid is not None:
                    preds = [last_leaf_uid]
                    deps += 1

                write_task(
                    out,
                    uid=uid,
                    tid=tid,
                    name=name,
                    outline_level=2,
                    outline_number=f"{phase_no}.{task_no}",
                    wbs=f"{phase_no}.{task_no}",
                    summary=False,
                    start=t_start,
                    finish=t_end,
                    duration="PT24H0M0S",
                    predecessors=preds,
                )
                last_leaf_uid = uid
                uid += 1
                tid += 1
                leaf += 1

        out.write(
            """  </Tasks>
  <Resources/>
  <Assignments/>
</Project>
"""
        )

    size_mb = xml_path.stat().st_size / (1024 * 1024)
    print("wrote", xml_path)
    print(f"phases={PHASE_COUNT} leaf_tasks={leaf} dependencies={deps} size_mb={size_mb:.1f}")
    print()
    print("Import via: project workspace → Import MPP → workspace-mpp-20000.xml")


if __name__ == "__main__":
    main()
