version: '3.8'

services:
  postgres:
    image: postgres:17.6-alpine
    ports:
      - "5435:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./backend/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: m123
      POSTGRES_DB: cybsec_pmo

  redis:
    image: redis:7-alpine
    ports:
      - "6378:6379"

  maildev:
    image: maildev/maildev:2.1.0
    ports:
      - "1080:1080"
      - "1025:1025"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "/opt/wait-for-it.sh postgres:5432 -- npx prisma migrate deploy && npx prisma db seed && npm run start:dev"
    ports:
      - "6001:6001"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_URL=postgresql://postgres:m123@postgres:5432/cybsec_pmo?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - WORKER_HOST=redis://redis:6379/1
    depends_on:
      - postgres
      - redis

  frontend:
    image: node:22.18.0-slim
    working_dir: /app
    command: sh -c "npm install --no-package-lock --os=linux --cpu=x64 && npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend

volumes:
  postgres_dev_data:
