export const NOTIFICATIONS_QUEUE = 'notifications';

export const NOTIFICATION_EMAIL_JOB = 'send-notification-email';

export const NOTIFICATION_DELIVERY_CHANNEL = {
  IN_APP: 'in_app',
  EMAIL: 'email',
} as const;

export const NOTIFICATION_DELIVERY_STATUS = {
  QUEUED: 'queued',
  SENT: 'sent',
  FAILED: 'failed',
  SKIPPED: 'skipped',
} as const;

export const NOTIFICATION_EVENT_TYPE = {
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  TASK_UPDATED: 'TASK_UPDATED',
  PROGRESS_SUBMITTED: 'PROGRESS_SUBMITTED',
  PROGRESS_APPROVED: 'PROGRESS_APPROVED',
  PROGRESS_REJECTED: 'PROGRESS_REJECTED',
  PROGRESS_REWORK: 'PROGRESS_REWORK',
  DEPENDENCY_SCHEDULE_IMPACT: 'DEPENDENCY_SCHEDULE_IMPACT',
  TIMESHEET_SUBMITTED: 'TIMESHEET_SUBMITTED',
  TIMESHEET_RESUBMITTED: 'TIMESHEET_RESUBMITTED',
  TIMESHEET_APPROVED: 'TIMESHEET_APPROVED',
  TIMESHEET_REJECTED: 'TIMESHEET_REJECTED',
  TIMESHEET_ESCALATED: 'TIMESHEET_ESCALATED',
  LEAVE_CRITICAL_CONFLICT: 'LEAVE_CRITICAL_CONFLICT',
  ACTION_POINT_ASSIGNED: 'ACTION_POINT_ASSIGNED',
  ACTION_POINT_OVERDUE: 'ACTION_POINT_OVERDUE',
  TASK_DEADLINE_REMINDER: 'TASK_DEADLINE_REMINDER',
} as const;

export type NotificationEventType =
  (typeof NOTIFICATION_EVENT_TYPE)[keyof typeof NOTIFICATION_EVENT_TYPE];

export const NOTIFICATIONS_SOCKET_NAMESPACE = 'notifications';

export const notificationUserRoom = (userId: string): string => `user:${userId}`;
