apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30601
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aynuayex/cybersec-pmo:backend
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_PORT
              value: "3000"
            - name: API_PREFIX
              value: "api"
            - name: DATABASE_HOST
              value: "postgres"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USERNAME
              value: "root"
            - name: DATABASE_PASSWORD
              value: "secret"
            - name: DATABASE_NAME
              value: "api"
            - name: DATABASE_URL
              value: "postgresql://root:secret@postgres:5432/api?schema=public"
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"
            - name: FRONTEND_DOMAIN
              value: "https://cybsec.addisanalytics.com"
            - name: BACKEND_DOMAIN
              value: "https://cybsec.addisanalytics.com"
            - name: AUTH_JWT_SECRET
              value: "change-me-to-a-secure-random-key"
            - name: AUTH_REFRESH_SECRET
              value: "change-me-to-another-secure-random-key"
            - name: AUTH_FORGOT_SECRET
              value: "change-me-to-forgot-secure-random-key"
            - name: AUTH_CONFIRM_EMAIL_SECRET
              value: "change-me-to-confirm-secure-random-key"
            - name: SECURITY_ALERTS_ENABLED
              value: "true"
            - name: SECURITY_ALERT_EMAIL
              value: "bminilik12@gmail.com"
            - name: ENTRA_TENANT_ID
              value: "301b9d6d-03a0-4afa-994d-367a03b30b5a"
            - name: ENTRA_CLIENT_ID
              value: "1977447d-18f8-4fa3-9be1-4d2b196e0ede"
            - name: ENTRA_CLIENT_SECRET
              value: "change-me-to-your-entra-client-secret"
            - name: ENTRA_REDIRECT_URI
              value: "https://cybsec.addisanalytics.com/api/v1/auth/entra/callback"
            - name: MAIL_HOST
              value: "smtp.gmail.com"
            - name: MAIL_PORT
              value: "587"
            - name: MAIL_USER
              value: "bminilik12@gmail.com"
            - name: MAIL_PASSWORD
              value: "change-me-to-your-mail-password"
            - name: MAIL_IGNORE_TLS
              value: "false"
            - name: MAIL_SECURE
              value: "false"
            - name: MAIL_REQUIRE_TLS
              value: "true"
            - name: MAIL_DEFAULT_EMAIL
              value: "noreply@paini.com"
            - name: MAIL_DEFAULT_NAME
              value: "Konax"
            - name: BREAK_GLASS_ENABLED
              value: "true"
            - name: BREAK_GLASS_EMERGENCY_SECRET
              value: "change-me-to-your-break-glass-secret"
      imagePullSecrets:
        - name: dockerhub-registry

