export const DATA_QUALITY_FLAG_TYPE = {
  MISSING_TIMESHEET: 'MISSING_TIMESHEET',
  UNAPPROVED_TIMESHEET: 'UNAPPROVED_TIMESHEET',
  STALE_INTEGRATION: 'STALE_INTEGRATION',
  INCOMPLETE_PROJECT: 'INCOMPLETE_PROJECT',
} as const;

export type DataQualityFlagType =
  (typeof DATA_QUALITY_FLAG_TYPE)[keyof typeof DATA_QUALITY_FLAG_TYPE];

export const DATA_QUALITY_SEVERITY = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical',
} as const;

export const KEKA_INTEGRATION_FLAG_ID = '00000000-0000-0000-0000-000000000003';
