import type { TeamDirectoryMember } from "../types/resources.types";

export const TEAM_DIRECTORY_MEMBERS: TeamDirectoryMember[] = [
  {
    id: "emp-rachel",
    name: "Rachel Green",
    initials: "RG",
    color: "bg-violet-500",
    designation: "Team Lead",
    department: "Security Operations Center",
    email: "rachelgreen@bminilik12gmail.onmicrosoft.com",
    utilization: 85,
    weeklyCapacity: 40,
    allocatedHours: 34,
    remainingHours: 6,
    projects: ["SOC Platform Rollout"],
    kekaEmployeeId: "6b153a31-7017-47f3-ba01-4f8a9257b5f1",
    kekaSyncStatus: "synced",
    utilStatus: "optimal",
    assignments: [
      {
        project: "SOC Platform Rollout",
        role: "Team Lead",
        hoursPerWeek: 24,
        allocationPercent: 60,
        startDate: "Jan 2026",
        endDate: "Jun 2026",
        status: "active",
      },
    ],
    upcomingLeave: [],
    leaveHistory: [],
  },
  {
    id: "emp-brian",
    name: "Brian Nguyen",
    initials: "BN",
    color: "bg-sky-500",
    designation: "Security Consultant",
    department: "Security Operations Center",
    email: "briannguyen@bminilik12gmail.onmicrosoft.com",
    utilization: 95,
    weeklyCapacity: 40,
    allocatedHours: 38,
    remainingHours: 2,
    projects: ["SOC Platform Rollout", "Client IR Retainer"],
    kekaEmployeeId: "39663c6a-d8d6-49e2-aabd-a366a66fb2c2",
    kekaSyncStatus: "synced",
    utilStatus: "over",
    manager: "Rachel Green",
    assignments: [
      {
        project: "SOC Platform Rollout",
        role: "Security Consultant",
        hoursPerWeek: 20,
        allocationPercent: 50,
        startDate: "Feb 2026",
        endDate: "Jul 2026",
        status: "active",
      },
      {
        project: "Client IR Retainer",
        role: "Lead Consultant",
        hoursPerWeek: 18,
        allocationPercent: 45,
        startDate: "Mar 2026",
        endDate: "Sep 2026",
        status: "active",
      },
    ],
    upcomingLeave: [],
    leaveHistory: [
      {
        id: "leave-001",
        type: "Annual Leave",
        from: "In 7 days",
        to: "In 7 days",
        days: 1,
        status: "approved",
        reason: "Personal day",
        approvedBy: "Rachel Green",
      },
    ],
  },
  {
    id: "emp-emily",
    name: "Emily Davis",
    initials: "ED",
    color: "bg-emerald-500",
    designation: "GRC Analyst",
    department: "Governance, Risk & Compliance",
    email: "emilydavis@bminilik12gmail.onmicrosoft.com",
    utilization: 72,
    weeklyCapacity: 40,
    allocatedHours: 29,
    remainingHours: 11,
    projects: ["ISO 27001 Readiness"],
    kekaEmployeeId: "c5e1a9ee-3753-4a32-aaa1-0a31c5d30c74",
    kekaSyncStatus: "synced",
    utilStatus: "optimal",
    manager: "Rachel Green",
    assignments: [
      {
        project: "ISO 27001 Readiness",
        role: "GRC Analyst",
        hoursPerWeek: 28,
        allocationPercent: 70,
        startDate: "Jan 2026",
        endDate: "Aug 2026",
        status: "active",
      },
    ],
    upcomingLeave: [],
    leaveHistory: [
      {
        id: "leave-002",
        type: "Sick Leave",
        from: "In 14 days",
        to: "In 15 days",
        days: 2,
        status: "approved",
        approvedBy: "Rachel Green",
      },
    ],
  },
  {
    id: "emp-sarah",
    name: "Sarah Jenkins",
    initials: "SJ",
    color: "bg-amber-500",
    designation: "Cloud Security Engineer",
    department: "Cloud Security",
    email: "sarahjenkins@bminilik12gmail.onmicrosoft.com",
    utilization: 55,
    weeklyCapacity: 40,
    allocatedHours: 22,
    remainingHours: 18,
    projects: ["Cloud Landing Zone"],
    kekaEmployeeId: "b2222222-2222-4222-8222-222222222201",
    kekaSyncStatus: "synced",
    utilStatus: "under",
    manager: "Rachel Green",
    assignments: [
      {
        project: "Cloud Landing Zone",
        role: "Cloud Security Engineer",
        hoursPerWeek: 22,
        allocationPercent: 55,
        startDate: "Feb 2026",
        endDate: "Oct 2026",
        status: "active",
      },
    ],
    upcomingLeave: [],
    leaveHistory: [
      {
        id: "leave-003",
        type: "Annual Leave",
        from: "In 21 days",
        to: "In 21 days",
        days: 1,
        status: "pending",
        reason: "Half day",
      },
    ],
  },
];
