import type {
  TimesheetEntry,
  TimesheetSubmission,
  TimesheetWeekSummary,
} from "../types/resources.types";

export const TIMESHEET_PROJECTS = [
  {
    id: "soc",
    name: "SOC Platform Rollout",
    tasks: ["SIEM tuning", "Playbook authoring", "Client onboarding", "Detection review"],
  },
  {
    id: "grc",
    name: "ISO 27001 Readiness",
    tasks: ["Control mapping", "Policy review", "Evidence collection", "Gap analysis"],
  },
  {
    id: "cloud",
    name: "Cloud Landing Zone",
    tasks: ["IAM baseline", "Network segmentation", "Guardrails", "Security review"],
  },
  {
    id: "ir",
    name: "Client IR Retainer",
    tasks: ["Triage", "Containment", "Reporting", "Lessons learned"],
  },
];

export const INITIAL_TIMESHEET_ENTRIES: TimesheetEntry[] = [
  {
    id: "e1",
    date: "2026-07-04",
    project: "SOC Platform Rollout",
    task: "Playbook authoring",
    hours: 4.5,
    description: "Drafted escalation playbooks for tier-1 alerts.",
    status: "draft",
  },
  {
    id: "e2",
    date: "2026-07-04",
    project: "Client IR Retainer",
    task: "Triage",
    hours: 3,
    description: "Reviewed suspicious sign-in alerts.",
    status: "draft",
  },
  {
    id: "e3",
    date: "2026-07-03",
    project: "SOC Platform Rollout",
    task: "SIEM tuning",
    hours: 6,
    description: "Tuned correlation rules for VPN anomalies.",
    status: "submitted",
  },
  {
    id: "e4",
    date: "2026-07-02",
    project: "ISO 27001 Readiness",
    task: "Control mapping",
    hours: 7.5,
    description: "Mapped Annex A controls to current policies.",
    status: "approved",
    approvedBy: "Rachel Green",
  },
  {
    id: "e5",
    date: "2026-07-01",
    project: "Cloud Landing Zone",
    task: "IAM baseline",
    hours: 3,
    description: "Workshop notes need more detail.",
    status: "rejected",
    feedback: "Please add specific IAM controls reviewed.",
  },
];

export const TIMESHEET_WEEK_SUMMARIES: TimesheetWeekSummary[] = [
  { week: "Jun 30 – Jul 4, 2026", totalHours: 24, billableHours: 22, status: "draft" },
  {
    week: "Jun 23 – 27, 2026",
    totalHours: 40,
    billableHours: 38,
    status: "approved",
    submittedAt: "Jun 28",
    approvedBy: "Rachel Green",
  },
];

export const TIMESHEET_SUBMISSIONS: TimesheetSubmission[] = [
  {
    id: "ts1",
    employeeId: "emp-1",
    employee: "Brian Nguyen",
    employeeInitials: "BN",
    employeeRole: "Security Consultant",
    weekStart: "2026-06-30",
    week: "Jun 30 – Jul 4, 2026",
    submittedAt: "Jul 4, 17:30",
    totalHours: 42,
    billableHours: 40,
    status: "pending",
    isOverThreshold: true,
    isEscalated: false,
    hasSyncFailures: false,
    failedSyncCount: 0,
    feedback: null,
    entries: [
      { id: "ts1-e1", date: "Jul 1", project: "SOC Platform Rollout", task: "SIEM tuning", hours: 8, description: "Rule tuning." },
      { id: "ts1-e2", date: "Jul 2", project: "Client IR Retainer", task: "Triage", hours: 9, description: "Incident review." },
      { id: "ts1-e3", date: "Jul 3", project: "SOC Platform Rollout", task: "Playbook authoring", hours: 8.5, description: "Playbooks." },
      { id: "ts1-e4", date: "Jul 4", project: "Client IR Retainer", task: "Reporting", hours: 8.5, description: "Client report." },
    ],
  },
  {
    id: "ts2",
    employeeId: "emp-2",
    employee: "Emily Davis",
    employeeInitials: "ED",
    employeeRole: "GRC Analyst",
    weekStart: "2026-06-30",
    week: "Jun 30 – Jul 4, 2026",
    submittedAt: "Jul 4, 16:00",
    totalHours: 36,
    billableHours: 34,
    status: "pending",
    isOverThreshold: false,
    isEscalated: false,
    hasSyncFailures: false,
    failedSyncCount: 0,
    feedback: null,
    entries: [
      { id: "ts2-e1", date: "Jul 1", project: "ISO 27001 Readiness", task: "Control mapping", hours: 7, description: "Annex A mapping." },
      { id: "ts2-e2", date: "Jul 2", project: "ISO 27001 Readiness", task: "Evidence collection", hours: 8, description: "Evidence pack." },
      { id: "ts2-e3", date: "Jul 3", project: "ISO 27001 Readiness", task: "Gap analysis", hours: 7, description: "Gap review." },
      { id: "ts2-e4", date: "Jul 4", project: "ISO 27001 Readiness", task: "Policy review", hours: 7, description: "Policy updates." },
    ],
  },
  {
    id: "ts3",
    employeeId: "emp-3",
    employee: "Sarah Jenkins",
    employeeInitials: "SJ",
    employeeRole: "Cloud Security Engineer",
    weekStart: "2026-06-23",
    week: "Jun 23 – 27, 2026",
    submittedAt: "Jun 27, 18:00",
    totalHours: 38,
    billableHours: 36,
    status: "approved",
    isOverThreshold: false,
    isEscalated: false,
    hasSyncFailures: false,
    failedSyncCount: 0,
    feedback: null,
    entries: [
      { id: "ts3-e1", date: "Jun 23", project: "Cloud Landing Zone", task: "Guardrails", hours: 8, description: "SCP design." },
      { id: "ts3-e2", date: "Jun 24", project: "Cloud Landing Zone", task: "IAM baseline", hours: 7.5, description: "Role design." },
      { id: "ts3-e3", date: "Jun 25", project: "Cloud Landing Zone", task: "Network segmentation", hours: 8, description: "VPC layout." },
      { id: "ts3-e4", date: "Jun 26", project: "Cloud Landing Zone", task: "Security review", hours: 7.5, description: "Architecture review." },
      { id: "ts3-e5", date: "Jun 27", project: "Cloud Landing Zone", task: "Guardrails", hours: 7, description: "Implementation." },
    ],
  },
];
